name: ParkourPlugin
main: aybici.parkourplugin.ParkourPlugin
softdepend: [Multiverse-Core]
version: 0.1
api-version: 1.16
commands:
  pklist:
  times:
  apk:
  playdemo:
    description: play demo of player in this parkour
    usage: /playdemo <player>
  showlasttry:
    description: plays demo of last try in parkour
    usage: /showlasttry
  cp:
    description: Sets checkpoint
    usage: /cp
  setlobby:
    description: Sets lobby location to player location
    usage: /setlobby
  pkquit:
    description: Quits parkour
    usage: /pkquit
  lobby:
    description: Quits parkour and teleports to lobby
    usage: /lobby [tpall]
  ping:
    description: Shows your ping
    usage: /ping
  hide:
    description: Hide or show all players
    usage: /hide <on/off>
  fails:
    description: Display number of fails on parkour
    usage: /fails
  pk:
    description: Teleport to a parkour
    usage: /pk <pkname> (WARNING! replace " " to "_"); /pk <category> <ID>; try also /pklist;
  pkat: